application: github-alert
version: 1
runtime: go
api_version: go1

env_variables:
  CORP_ID: 'dingaxxxx'
  CORP_SECRET: 'xxxxxxxxxxxx'
  GITHUB_WEBHOOK_SECRET: 'xxxxxxxxxxxx'
  SENDER_ID: '011217462940'
  CHAT_ID: 'chat6a93bc1ee3b7d660d372b1b877a9de62'

handlers:
- url: /.*
  script: _go_app